/*****************************************************************************
  FILE              : co_pFuncs.c
  SHORTNAME         : pFuncs
  VERSION           : 2.0

  PURPOSE           : Auxiliar functions for use with parser generated by yacc.
                      Included into co_parser.c.
  NOTES             :

  AUTHOR            : Thomas Korb
  DATE              : 27.6.1991

  CHANGED BY        :
  IDENTIFICATION    : %W% %G%
  SCCS VERSION      : %I%
  LAST CHANGE       : %G%

             (c) 1991 by Thomas Korb and the SNNS-Group

******************************************************************************/

#include "co_pFuncs.h"


/**** static variables ****/

ParserStackType *PA_ProgramArguments;           /* compile time defined argument values */
static ParserStackType *PA_FreeParserPtr; /* stack of unused parser value stack records */




/*****************************************************************************************
 Function:                     PA_Parser
 Purpose: Initializes parser and scanner input. Calls function yyparse built by yacc.
 Returns: Result of yyparse.
 Side effects: Modifies stack of input files.
*****************************************************************************************/
int PA_Parser(InFile, NetArgStack, XAdd, YAdd)
ParserStackType *InFile;                          /* holds constant for input file */
ParserStackType *NetArgStack;                       /* stack of program attributes */
ParserStackType *XAdd;                            /* to transform subnet positions */
ParserStackType *YAdd;
{
    /* This originally implemented recursive/nested parsing of a subnet
       definition file mid-parse, by manually saving and restoring the
       internal global parser/scanner state (yyval, yychar, yysptr,
       yylsp, struct yysvf/yywork, etc.) of the original AT&T/Berkeley
       yacc and lex this file was written against. Modern GNU Bison and
       Flex don't expose that internal state at all - their generated
       parsers use local variables with a different structure entirely
       - so this technique cannot work with the current toolchain.
       Nested subnet includes (SUBNET ... AT ...) are unsupported until
       this is redesigned around a reentrant parser. */
    ER_StackError("nested subnet includes are not supported in this build\n",
                  Fatal, nst, nst, nst);
    PA_FreeParserStack(XAdd);
    PA_FreeParserStack(YAdd);
    PA_FreeParserStack(InFile);
    return TRUE;
}





/*****************************************************************************************
 Function:                     PA_GetParserStack
 Purpose: Allocates and initializes a new parser stack record, if there are no records free.
 Returns: & ParserStackType.
 Side effects: Modifies PA_FreeParserPtr
*****************************************************************************************/
ParserStackType *PA_GetParserStack() {
    register ParserStackType *p;       /* pointer to new parser stack record */

    if(PA_FreeParserPtr)
        PA_FreeParserPtr = (p=PA_FreeParserPtr)->ynext;
    else {
        p = (ParserStackType *) (M_alloc(sizeof(ParserStackType)));
        p->yvalue = (SymbolValueType *) (M_alloc(sizeof(SymbolValueType)));
    }
    p->ynext = NULL;
    p->ytype = Undef;
    return p;
}





/*****************************************************************************************
 Function:                     PA_FreeParserStack
 Purpose: Push an unused ParserStackType record on the stack PA_FreeParserPtr.
          ->Value is preserved.
 Returns: void
 Side effects: Modifies PA_FreeParserPtr.
*****************************************************************************************/
void PA_FreeParserStack(p)
register ParserStackType *p;
{
    if(p) {
        p->ynext = PA_FreeParserPtr;
        PA_FreeParserPtr = p;
    }
}




/*****************************************************************************************
 Function:                     PA_GetUndefValue
 Purpose: Allocates and initializes a new parser stack record whose ytype component is
          Undef. This is needed to signalize errors to functions that perform other
	  semantic actions.
 Returns: & ParserStackType.
*****************************************************************************************/
ParserStackType *PA_GetUndefValue() {
    register ParserStackType *p;       /* pointer to new parser stack record */

    p = PA_GetParserStack();
    p->ytype = Undef;
    return p;
}





/*****************************************************************************************
 Function:                     PA_GetUndefString
 Purpose: Allocates and initializes a new parser stack record whose ytype component is
          string. Needed to distinguish undefined strings from illegal expressions. The
	  string value is set to NULL.
 Returns: & ParserStackType.
*****************************************************************************************/
ParserStackType *PA_GetUndefString() {
    register ParserStackType *p;       /* pointer to new parser stack record */

    p = PA_GetParserStack();
    p->ytype = SIMPLESTRING;
    p->yvalue->string = NULL;
    return p;
}








/*****************************************************************************************
 Function:                     yyNewerror
 Purpose: imprved error reports.
 NOTE: copied from Schreiner, Friedman: Introduction to Compiler Construction with UNIX,
       (C) 1985 Prentice-Hall, pp. 235-239. Modified.
*****************************************************************************************/
void yyNewerror(s,t)
register char *s, *t;
{
    extern int yynerrs;
    static int list = 0;

    char *ErrBuf, *Old;

    if(s  || ! list) {                                /* header for error message needed? */
        ErrBuf = STR_Save("syntax: ");
        /* yywhere(); not copied */
        if(s)  {                                                    /* simple error message */
            Old = ErrBuf;
            ErrBuf = STR_Append(ErrBuf, s);
            M_free(Old);
            ER_StackError(STR_Append(ErrBuf, "\n"), Fatal, nst,  nst, nst);  /* print message */
            ErrBuf = NULL;
            return;
        }
        if(t) {                                                           /* first symbol ? */
            Old = ErrBuf;
            ErrBuf = STR_Append(ErrBuf, "expecting '");
            M_free(Old);
            Old = ErrBuf;
            ErrBuf = STR_Append(ErrBuf, t);
            M_free(Old);
            list  = 1;        /* do  not print error message, wait for other expected symbols */
            return;
        }
        /* no symbols can be inserted for a legal reduction */
        ER_StackError(STR_Save("syntax\n"), Fatal, nst, nst, nst);
        return;
    }
    if(t) {                                                    /* more symbols expected ? */
        Old = ErrBuf;
        ErrBuf = STR_Append(ErrBuf, " ");
        M_free(Old);
        Old = ErrBuf;
        ErrBuf = STR_Append(ErrBuf, t);
        M_free(Old);
    }
    ER_StackError(STR_Append(ErrBuf, "'\n"), Fatal, nst,  nst, nst);/* no further  symbols */
    ErrBuf = NULL;                                                 /* print error message */
    list = 0;
}
